<?php

/**
 * @file
 * Allows users to create and organize related content in an outline.
 */

/*return values*/
/*
#1"title":
#2"title callback":
#3"title arguments":
#4"description":
#5"page callback":
#6"page arguments":
#7"delivery callback":
#8"access callback":
#9"access arguments":
10"theme callback":
11"theme arguments":
12"file path":
13"load arguments":
"weight":
"menu_name":
"expanded":
"context":
"tab_parent"
"tab_root":
"position":
"type":
"options":
*/


/**
 * Implements hook_menu().
 */
function menu_routing_menu(){// arg/origin/destination
  $items['menu/routing/first/%/%/%'] = array(
    #1
    'title' => 'Example menu',
    #2
    'title callback' => 'example_title_callback',
    #3
    'title arguments' => array(1),
    #4
    'description' => 'Example description',
    #5
    'page callback' => 'menu_routing_example_menu',
    #6
    'page arguments' => array(0,1,2),
    #7
    'delivery callback' => 'example_deliver_page',
    #8
    'access callback' => 'example_acces_callback',// user_access() - default
    #9
    'access arguments' => array('first','second'),
    #10
    'theme callback' => 'variable_get',
    #11
    'theme arguments' => array('admin_theme'),//Example system -menu - admin
    #12
    'file' => 'example.inc',

    'type' => MENU_CALLBACK,
  );
  return $items;
}


