<?php

/**
 * @file
 * Allows users to create and organize related content in an outline.
 */

/**
 * Implements hook_menu().
 */
function menu_routing_menu(){
  $items['menu/routing/first'] = array(
    'title' => 'Path concept',
    'page callback' => 'menu_routing_path_concept_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


function menu_routing_path_concept_callback(){
  return 'h1';
}


/*return values*/
/*
"title":
"title callback":
"title arguments":
"description":
"page callback":
"page arguments":
"delivery callback":
"access callback":
"access arguments":
"theme callback":
"theme arguments":
"file path":
"load arguments":
"weight":
"menu_name":
"expanded":
"context":
"tab_parent"
"tab_root":
"position":
"type":
"options":
*/