<?php
/**
 * @file
 * Form api examples
 */

/**
 * Implements hook_menu().
 */
function fom_api_menu() {
  $items['form/api/example/form'] = array(
    'title' => 'View the sample form',
    'page callback' => 'drupal_get_form',
    'access callback' => true,

  );

  return $items;
}

function for_api_example_form(){

  $render_example = array();
}



function for_api_elements_info(){
 return array(
    'new_form_type' => array(
      '#input' => TRUE,
      '#tree' => TRUE,
      '#process' => array('_new_form_type_process'),
      '#value_callback' => '_new_form_type_value_callback',
  ));

}
